table = 'auth_permission'
fields = ['id', 'name', 'content_type_id', 'codename']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[1, u'Can add permission', 1, u'add_permission']
[2, u'Can change permission', 1, u'change_permission']
[3, u'Can delete permission', 1, u'delete_permission']
[4, u'Can add group', 2, u'add_group']
[5, u'Can change group', 2, u'change_group']
[6, u'Can delete group', 2, u'delete_group']
[7, u'Can add user', 3, u'add_user']
[8, u'Can change user', 3, u'change_user']
[9, u'Can delete user', 3, u'delete_user']
[10, u'Can add message', 4, u'add_message']
[11, u'Can change message', 4, u'change_message']
[12, u'Can delete message', 4, u'delete_message']
[13, u'Can add content type', 5, u'add_contenttype']
[14, u'Can change content type', 5, u'change_contenttype']
[15, u'Can delete content type', 5, u'delete_contenttype']
[16, u'Can add session', 6, u'add_session']
[17, u'Can change session', 6, u'change_session']
[18, u'Can delete session', 6, u'delete_session']
[19, u'Can add site', 7, u'add_site']
[20, u'Can change site', 7, u'change_site']
[21, u'Can delete site', 7, u'delete_site']
[22, u'Can add factor', 8, u'add_factor']
[23, u'Can change factor', 8, u'change_factor']
[24, u'Can delete factor', 8, u'delete_factor']
[25, u'Can add answer', 9, u'add_answer']
[26, u'Can change answer', 9, u'change_answer']
[27, u'Can delete answer', 9, u'delete_answer']
[28, u'Can add log entry', 10, u'add_logentry']
[29, u'Can change log entry', 10, u'change_logentry']
[30, u'Can delete log entry', 10, u'delete_logentry']
[31, u'Can add technology group', 13, u'add_techgroup']
[32, u'Can change technology group', 13, u'change_techgroup']
[33, u'Can delete technology group', 13, u'delete_techgroup']
[34, u'Can add technology', 11, u'add_technology']
[35, u'Can change technology', 11, u'change_technology']
[36, u'Can delete technology', 11, u'delete_technology']
[37, u'Can add note', 14, u'add_note']
[38, u'Can change note', 14, u'change_note']
[39, u'Can delete note', 14, u'delete_note']
[40, u'Can add Appropriatness', 12, u'add_relevancy']
[41, u'Can change Appropriatness', 12, u'change_relevancy']
[42, u'Can delete Appropriatness', 12, u'delete_relevancy']
]
