table = 'dst_factor'
fields = ['id', 'factor', 'order', 'info_heading', 'info_text']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[1, u'Water supply', 10, u'Availability of water', u'This factor determines how much water is available for toilet use, and where it comes from. The items are ordered from no water to plenty of water available.']
[2, u'Space availability', 20, u'Maecenas tempus dictum libero', u'Donec gravida posuere arcu. Nulla facilisi. Phasellus imperdiet. Vestibulum at metus. Integer euismod. Nullam placerat rhoncus sapien. Ut euismod. Praesent libero. Morbi pellentesque libero sit amet ante. Maecenas tellus. Maecenas erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.']
[3, u'Flood prone', 30, u'Cras magna ante', u'Ut nulla. Vivamus bibendum, nulla ut congue fringilla, lorem ipsum ultricies risus, ut rutrum velit tortor vel purus. In hac habitasse platea dictumst. Duis fermentum, metus sed congue gravida, arcu dui ornare urna, ut imperdiet enim odio dignissim ipsum. Nulla facilisi. Cras magna ante, bibendum sit amet, porta vitae, laoreet ut, justo. Nam tortor sapien, pulvinar nec, malesuada in, ultrices in, tortor. Cras ultricies placerat eros. Quisque odio eros, feugiat non, iaculis nec, lobortis sed, arcu. Pellentesque sit amet sem et purus pretium consectetuer.']
[4, u'Groundwater table', 40, u'Depth of the groundwater', u'The depth of the groundwater table is important, because when the table is too high, latrines with an open bottom are not an option, and closed tanks or sewerage systems need to be used.']
[5, u'Terrain / Topography / Slope', 50, u'Lorem ipsum dolor sit amet', u'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In diam urna, laoreet ut malesuada quis, lacinia sit amet lorem. Suspendisse vel sollicitudin neque. Proin et dui at sapien tincidunt ullamcorper gravida ac nisl. Mauris nec dapibus dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin dolor ante, egestas venenatis condimentum ac, laoreet non orci. Cras orci arcu, aliquam nec faucibus sagittis, ultrices in erat. In hac habitasse platea dictumst. \r\n\r\n']
[6, u'Vehicular accessibility', 60, u'Can vehicules access the site easily?', u'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In diam urna, laoreet ut malesuada quis, lacinia sit amet lorem. Suspendisse vel sollicitudin neque. Proin et dui at sapien tincidunt ullamcorper gravida ac nisl. Mauris nec dapibus dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin dolor ante, egestas venenatis condimentum ac, laoreet non orci. Cras orci arcu, aliquam nec faucibus sagittis, ultrices in erat. In hac habitasse platea dictumst. ']
[7, u'Soil type', 70, u'The type of soil', u'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In diam urna, laoreet ut malesuada quis, lacinia sit amet lorem. Suspendisse vel sollicitudin neque. Proin et dui at sapien tincidunt ullamcorper gravida ac nisl. Mauris nec dapibus dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin dolor ante, egestas venenatis condimentum ac, laoreet non orci. Cras orci arcu, aliquam nec faucibus sagittis, ultrices in erat. In hac habitasse platea dictumst. ']
[8, u'Roads / Paths system', 80, u'Nature of the roads and paths', u'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In diam urna, laoreet ut malesuada quis, lacinia sit amet lorem. Suspendisse vel sollicitudin neque. Proin et dui at sapien tincidunt ullamcorper gravida ac nisl. Mauris nec dapibus dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin dolor ante, egestas venenatis condimentum ac, laoreet non orci. Cras orci arcu, aliquam nec faucibus sagittis, ultrices in erat. In hac habitasse platea dictumst. ']
[9, u'Anal cleansing method', 90, u'Method used for anal cleansing', u'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In diam urna, laoreet ut malesuada quis, lacinia sit amet lorem. Suspendisse vel sollicitudin neque. Proin et dui at sapien tincidunt ullamcorper gravida ac nisl. Mauris nec dapibus dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin dolor ante, egestas venenatis condimentum ac, laoreet non orci. Cras orci arcu, aliquam nec faucibus sagittis, ultrices in erat. In hac habitasse platea dictumst. ']
]
