table = 'dst_note'
fields = ['id', 'note']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[1, u'test note']
[2, u'Requires water for proper functioning']
[3, u'Requires a considerable amount of water']
[4, u'Clogging of water seal']
[5, u'Potential clogging of the water seal. A waste bin can be provided for disposal']
[6, u'Requires a reliable and constant source of water for proper functioning']
[7, u'Depends on the amount of space available. The tank can be installed underground']
[8, u'Special care in case of emptying and transport services requirement. Potential use of small vehicles']
[9, u'In high dense settlements limited digging of pit latrines']
[10, u'Limited soil infiltration and potential sludge overflow. High risk of groundwater pollution and dise']
[11, u'Difficulties for excavation.']
[12, u'In case of emptying services not available, attention to space limitations for digging new pits']
[13, u'Not recommended in potential flooding areas and high groundwater level']
[14, u'Special attention to land slide. Potential sip back to surface further down the slope']
[15, u'Vacuum tankers unsuitable. Potential use of small vehicles for desludging']
[16, u'Special attention to soil estability to avoid collapse of superstructure']
[17, u'In high dense settlements limited space for double pits']
[18, u'Limited soil infiltration and potential overflow. High risk of groundwater pollution and diseases']
[19, u'Attention to space requirements']
[20, u'Special attention to land slide. Potential sip back to surface further down the slope']
[21, u'Special care in case of emptying and transport services requirement. Potential use of small vehicles']
[22, u'Special attention to soil estability to avoid collapse of superstructure']
[23, u'In high dense settlements limited space for fossas alterna']
[24, u'Limited soil infiltration and potential overflow. High risk of groundwater pollution and diseases']
[25, u'Limited soil infiltration and potential overflow. High risk of groundwater pollution and diseases']
[26, u'Using hard or bulky materials reduces considerably the time to fill up']
[27, u'Requires some sort of access for desludging or emptying/transport']
[28, u'Special attention to heavy loads in steep slopes']
[29, u'Attention to access availability']
[30, u'Requires access for desludging']
[31, u'Special vehicles might be required (i.e. vacutug)']
[32, u'If vacuum suction systems are used special attention to hose obstruction']
[33, u'Requires a reliable source of water']
[34, u'Potential clogging of the pipes']
[35, u'If long distances are required, a pumping station might be needed']
[36, u'Difficulties for excavation. Special attention to the costs']
[37, u'Requires a considerable space available for construction']
[38, u'Requires access for emptying sludge']
[39, u'Difficulties for excavation. Special attention to the costs. Not recommended']
[40, u'Depending on the size of the tank, space availability could be a problem']
[41, u'Ensure sealing of the tank. Risk of water infiltration and overflow as well as leaking and groundwat']
[42, u'Requires a relatively small space available for construction']
[43, u'Depending on the size of the filter, space availability could be a problem']
[44, u'Requires a large space available for construction']
[45, u'High risk of leakage pollution and overflow']
[46, u'Depending on the size of the ponds, space availability could be a problem']
[47, u'Ensure lining of the ponds. Risk of water infiltration and overflow as well as leaking and groundwat']
[48, u'Requires large, relatively flat land']
[49, u'Depending on the size of the pond, space availability could be a problem']
[50, u'Space limitations for digging new pits.']
[51, u'Attention to space limitations for digging new pits.']
[52, u'Attention to space limitations for infiltration']
[53, u'In high dense settlements limited space for infiltration']
[54, u'Not recommended in low-laying areas and high groundwater level']
[55, u'Limited soil infiltration and potential overflow. High risk of groundwater pollution']
[56, u' Potential sip back to surface further down the slope']
[57, u'Difficulties for excavation and direct infiltration to groundwater.']
[58, u'Limited soil infiltration and potential overflow. High risk of groundwater pollution.']
[59, u'Attention to space limitations']
[60, u'Requires a large amount of space available']
[61, u'Attention to landslides.']
[62, u'Depending on the amount of sludge disposal, space availability could be a problem.']
[63, u'Requires a large space available for disposal.']
[64, u'Risk of ground water pollution.']
[65, u'High risk of groundwater pollution and diseases.']
[66, u'Requires some space available for disposal.']
[67, u' Attention to groundwater pollution.']
]
